// Generated by CoffeeScript 1.3.3
(function() {
  "use strict";

  var WeaponType, setWeaponTypes, weaponTypes;

  weaponTypes = [];

  WeaponType = (function() {

    function WeaponType(name, text, isRange) {
      this.name = name;
      this.text = text;
      this.isRange = isRange != null ? isRange : false;
    }

    WeaponType.prototype.getWeaponClass = function() {
      return "" + this.name + "-prop";
    };

    WeaponType.prototype.getRangeClass = function() {
      if (this.isRange) {
        return "range-weapon-prop";
      } else {
        return "close-weapon-prop";
      }
    };

    WeaponType.prototype.getClasses = function() {
      return [this.getWeaponClass(), this.getRangeClass()];
    };

    WeaponType.prototype.getText = function(lang) {
      return this.text[lang];
    };

    return WeaponType;

  })();

  setWeaponTypes = function(callback) {
    return $.getJSON("data/weapon_types.json", function(data) {
      var weaponType, _i, _len, _ref;
      _ref = data["weaponTypes"];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        weaponType = _ref[_i];
        weaponTypes.push(new WeaponType(weaponType["id"], weaponType["text"], weaponType["isRange"]));
      }
      return callback.call();
    });
  };

  $(function() {
    setWeaponTypes(function(data) {
      return console.log(weaponTypes);
    });
  });

}).call(this);
